---
version: "3.9"
services:
  terrarium:
    build:
      context: .
    ports:
      - 3000:3000
    command:
      - serve
      - module
      - --database-host
      - mongo:27017
  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - 8080:8080
volumes:
  data: