---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: terrarium-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: tag
      type: string
  resources:
    - name: terrarium-git
      type: git
    - name: terrarium-image
      type: image
  tasks:
    - name: build
      taskRef:
        name: docker-build
      params:
        - name: tag
          value: $(params.tag)
      resources:
        inputs:
          - name: source
            resource: terrarium-git
        outputs:
          - name: image
            resource: terrarium-image
    - name: push
      taskRef:
        name: docker-push
      params:
        - name: tag
          value: $(params.tag)
      resources:
        inputs:
          - name: image
            resource: terrarium-image
            from:
              - build