---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: terrarium-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
      description: Git repo URL to build docker image from
    - name: git-branch
      description: Git repo branch to build docker image from
    - name: docker-image-name
      description: "Name of resulting Docker Image"
    - name: docker-image-tag
      description: "Tag of resulting Docker Image"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: "terrarium-pipeline-"
      spec:
        pipelineRef:
          name: terrarium-pipeline
        serviceAccountName: tekton-builder
        params:
          - name: tag
            value: $(tt.params.docker-image-tag)
        resources:
          - name: terrarium-git
            resourceSpec: 
              type: git
              params:
                - name: url
                  value: $(tt.params.git-url)
                - name: revision
                  value: $(tt.params.git-branch)
          - name: terrarium-image
            resourceSpec: 
              type: image
              params:
                - name: url
                  value: $(tt.params.docker-image-name)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: terrarium-data
  namespace: tekton-pipelines
spec:
  params:
  - name: git-url
    value: $(body.repository.clone_url)
  - name: git-branch
    value: $(body.repository.master_branch)
  - name: docker-image-name
    value: "registry.dylanscott.me/terrarium"
  - name: docker-image-tag
    value: $(body.head_commit.id)