name: "terrarium-build-push"
on: ["push"]
jobs:
  build:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ""
      - run: ls -lah
      - run: docker build -t europe-west2-docker.pkg.dev/terrarium-330719/terrarium:latest .
      - run: docker push europe-west2-docker.pkg.dev/terrarium-330719/terrarium:latest
        
     